Update README.md (#1)
`getInfo` doesn't exist. I am using `getSpreadsheet` instead.

`mySheet.useServiceAccountAuth(credentials).then(mySheet.getInfo.bind(mySheet)).then(function (info) {
                                                                       ^
TypeError: Cannot read property 'bind' of undefined`